# The `FROM` instruction specifies the base image. We are extending the `microsoft/aspnet` image.
FROM microsoft/aspnet

# The final instruction copies the site you published earlier into the container.
COPY ./bin/Publishoutput/ /inetpub/wwwroot